### ISSUE TITLE
Error while loading OBJ mask.

### ISSUE THREAD

**Issue by RvMe** [futureperfectstudio/dreamfields-3D#1]
sometimes it can work 
sometimes it feedback error:

==> Saved obj to /home/hr/dreamfields-3D/output/trial/meshes/ngp_20.obj
Traceback (most recent call last):
  File "/home/hr/dreamfields-3D/main_nerf.py", line 129, in <module>
    trainer.train(train_loader, valid_loader, max_epoch, opt.mesh_res, opt.mesh_trh)
  File "/home/hr/dreamfields-3D/nerf/utils.py", line 692, in train
    self.save_mesh(resolution=mesh_res, threshold=mesh_trh)
  File "/home/hr/dreamfields-3D/nerf/utils.py", line 669, in save_mesh
    obj2ply(save_path)
  File "/home/hr/dreamfields-3D/nerf/utils.py", line 650, in obj2ply
    ms.load_new_mesh(obj_path)
pymeshlab.pmeshlab.PyMeshLabException: Unable to open file: trial/meshes/ngp_20.obj
Error while loading OBJ mask.

**Comment by Gotta-C** [comment]
same error
